language: c
script:
  - sudo apt-get update
  - chmod 777 build_linux.sh
  - ./build_linux.sh
sudo: true
addons:
  apt:
    packages:
      - build-essential
jobs:
  include:
    - stage: Code Coverage
        after_success:
          - coveralls --exclude tests --gcov-options '\-lp'
