version: build{build}
build_script:
  - choco install mingw
  - C:\tools\mingw64\bin\gcc.exe vm.c main.c -o main.exe
test: off
# test_script:
#   - cd c:\dev\install
#   - start /wait %example%.exe test
#   - cd c:\dev\examples
matrix:
  fast_finish: true
artifacts:
- path: '*.exe'
