version: build{build}
build_script:
  - choco install mingw
  - build_windows.bat
test: off
# test_script:
#   - cd c:\dev\install
#   - start /wait %example%.exe test
#   - cd c:\dev\examples
matrix:
  fast_finish: true
artifacts:
- path: '*.exe'
